comment:
  behavior: default
  layout: reach,diff,flags,tree
  require_changes: false

coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 80%
        threshold: 0%

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "cmd/**"
  - "internal/apptest/**"
  - "internal/eventtest/**"
  - "internal/testx/**"
