package orm

import "github.com/uptrace/bun/schema"

// ConstraintKind identifies the type of column constraint.
type ConstraintKind int

const (
	ConstraintNotNull ConstraintKind = iota
	ConstraintNullable
	ConstraintDefault
	ConstraintPrimaryKey
	ConstraintUnique
	ConstraintAutoIncrement
	ConstraintCheck
	ConstraintReferences
)

// ColumnConstraint represents a SQL column constraint such as NOT NULL, DEFAULT, PRIMARY KEY, etc.
type ColumnConstraint struct {
	kind         ConstraintKind
	defaultValue any
	checkBuilder func(ConditionBuilder)
	checkExpr    schema.QueryAppender
	refTable     string
	refColumns   []string
}

// compileChecks pre-compiles any CHECK condition against qb, returning a copy of
// the constraints with the compiled expression attached. It is called by the DDL
// query types at column-definition time, where a QueryBuilder is available, so
// the renderer never needs one and a CHECK can never fail late on a nil builder.
func compileChecks(qb QueryBuilder, constraints []ColumnConstraint) []ColumnConstraint {
	compiled := make([]ColumnConstraint, len(constraints))
	for i, c := range constraints {
		if c.kind == ConstraintCheck {
			// A nil checkBuilder (Check(nil) misuse) fails fast here via
			// BuildCondition's nil-func call, instead of silently rendering an
			// invalid `CHECK (?)` with a nil bound argument that errors at Exec.
			c.checkExpr = qb.BuildCondition(c.checkBuilder)
		}

		compiled[i] = c
	}

	return compiled
}

// NotNull creates a NOT NULL column constraint.
func NotNull() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintNotNull}
}

// Nullable creates an explicit NULL column constraint.
func Nullable() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintNullable}
}

// RawDefault is a raw SQL expression used as a column DEFAULT. Unlike a plain
// value, it is rendered verbatim (unquoted, no bound placeholder) so SQL
// functions and keywords such as CURRENT_TIMESTAMP or gen_random_uuid() work as
// defaults. The caller is responsible for the expression being valid for the
// target dialect; do not build it from untrusted input.
type RawDefault string

// Default creates a DEFAULT column constraint with the given value. String,
// boolean, and numeric values are rendered safely (literals through a bound
// placeholder where escaping is required); wrap a SQL function or keyword in
// RawDefault to render it verbatim.
func Default(value any) ColumnConstraint {
	return ColumnConstraint{kind: ConstraintDefault, defaultValue: value}
}

// PrimaryKey creates a PRIMARY KEY column constraint.
func PrimaryKey() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintPrimaryKey}
}

// Unique creates a UNIQUE column constraint.
func Unique() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintUnique}
}

// AutoIncrement creates an auto-increment column constraint.
// PostgreSQL: GENERATED BY DEFAULT AS IDENTITY, MySQL: AUTO_INCREMENT, SQLite: AUTOINCREMENT.
func AutoIncrement() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintAutoIncrement}
}

// Check creates a CHECK column constraint using the ConditionBuilder.
func Check(builder func(ConditionBuilder)) ColumnConstraint {
	return ColumnConstraint{kind: ConstraintCheck, checkBuilder: builder}
}

// References creates an inline foreign key column constraint.
func References(table string, columns ...string) ColumnConstraint {
	return ColumnConstraint{kind: ConstraintReferences, refTable: table, refColumns: columns}
}
