package orm

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect"
	"github.com/uptrace/bun/schema"
)

// TestDialect is a minimal DDLDialect implementation for unit testing renderers.
type TestDialect struct {
	name  dialect.Name
	quote byte
}

func (d TestDialect) Name() dialect.Name { return d.name }
func (d TestDialect) IdentQuote() byte   { return d.quote }

var (
	pgDialect     = TestDialect{dialect.PG, '"'}
	mysqlDialect  = TestDialect{dialect.MySQL, '`'}
	sqliteDialect = TestDialect{dialect.SQLite, '"'}
)

// TestQuoteIdent verifies identifier quoting with different quote characters.
func TestQuoteIdent(t *testing.T) {
	tests := []struct {
		name     string
		quote    byte
		ident    string
		expected string
	}{
		{"DoubleQuote", '"', "users", `"users"`},
		{"Backtick", '`', "users", "`users`"},
		{"EscapesEmbeddedQuote", '"', `user"name`, `"user""name"`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, quoteIdent(tt.quote, tt.ident),
				"Should quote the identifier correctly")
		})
	}
}

// TestJoinQuotedIdents verifies joining multiple quoted identifiers with commas.
func TestJoinQuotedIdents(t *testing.T) {
	tests := []struct {
		name     string
		quote    byte
		idents   []string
		expected string
	}{
		{"SingleIdent", '"', []string{"id"}, `"id"`},
		{"MultipleIdentsPG", '"', []string{"a", "b", "c"}, `"a", "b", "c"`},
		{"MultipleIdentsMySQL", '`', []string{"x", "y"}, "`x`, `y`"},
		{"EmptyInput", '"', nil, ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, joinQuotedIdents(tt.quote, tt.idents),
				"Should join identifiers correctly")
		})
	}
}

// TestRenderConstraint verifies SQL fragment rendering for each column constraint kind.
func TestRenderConstraint(t *testing.T) {
	tests := []struct {
		name       string
		constraint ColumnConstraint
		expected   string
	}{
		{"NotNull", NotNull(), "NOT NULL"},
		{"Nullable", Nullable(), "NULL"},
		{"PrimaryKey", PrimaryKey(), "PRIMARY KEY"},
		{"Unique", Unique(), "UNIQUE"},
		{"UnknownKind", ColumnConstraint{kind: ConstraintKind(999)}, ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, renderConstraint(pgDialect, tt.constraint),
				"Should render the correct constraint SQL")
		})
	}
}

// TestRenderDefault verifies DEFAULT clause rendering across types and dialects. NULL, booleans,
// and numerics render as keywords/literals with no bound args; RawDefault renders verbatim; every
// other value (strings, time.Time, []byte, custom types) is bound through a ? placeholder so the
// driver applies safe escaping rather than being interpolated raw.
func TestRenderDefault(t *testing.T) {
	ts := time.Date(2026, 6, 14, 10, 30, 0, 0, time.UTC)

	tests := []struct {
		name         string
		dialectName  dialect.Name
		value        any
		expected     string
		expectedArgs []any
	}{
		{"NilValue", dialect.PG, nil, "DEFAULT NULL", nil},
		{"StringValue", dialect.PG, "hello", "DEFAULT ?", []any{"hello"}},
		{"StringValueWithQuote", dialect.PG, "O'Reilly", "DEFAULT ?", []any{"O'Reilly"}},
		{"StringValueWithBackslash", dialect.MySQL, `a\'b`, "DEFAULT ?", []any{`a\'b`}},
		{"EmptyString", dialect.PG, "", "DEFAULT ?", []any{""}},
		{"IntValue", dialect.PG, 42, "DEFAULT 42", nil},
		{"UintValue", dialect.PG, uint(7), "DEFAULT 7", nil},
		{"FloatValue", dialect.PG, 3.14, "DEFAULT 3.14", nil},
		{"BoolTruePG", dialect.PG, true, "DEFAULT TRUE", nil},
		{"BoolFalsePG", dialect.PG, false, "DEFAULT FALSE", nil},
		{"BoolTrueMySQL", dialect.MySQL, true, "DEFAULT TRUE", nil},
		{"BoolTrueSQLite", dialect.SQLite, true, "DEFAULT 1", nil},
		{"BoolFalseSQLite", dialect.SQLite, false, "DEFAULT 0", nil},
		{"RawDefaultFunction", dialect.PG, RawDefault("CURRENT_TIMESTAMP"), "DEFAULT CURRENT_TIMESTAMP", nil},
		{"TimeValueBound", dialect.PG, ts, "DEFAULT ?", []any{ts}},
		{"ByteSliceBound", dialect.PG, []byte("x"), "DEFAULT ?", []any{[]byte("x")}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fragment, args := renderDefault(tt.dialectName, tt.value)
			assert.Equal(t, tt.expected, fragment, "Should render the correct DEFAULT clause")
			assert.Equal(t, tt.expectedArgs, args, "Should bind non-literal values and render numerics/RawDefault inline")
		})
	}
}

// TestRenderAutoIncrement verifies dialect-specific auto-increment syntax.
func TestRenderAutoIncrement(t *testing.T) {
	tests := []struct {
		name        string
		dialectName dialect.Name
		expected    string
	}{
		{"PostgreSQL", dialect.PG, "GENERATED BY DEFAULT AS IDENTITY"},
		{"MySQL", dialect.MySQL, "AUTO_INCREMENT"},
		{"SQLite", dialect.SQLite, "AUTOINCREMENT"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, renderAutoIncrement(tt.dialectName),
				"Should render dialect-specific auto-increment syntax")
		})
	}
}

// TestRenderInlineFK verifies inline REFERENCES clause rendering.
func TestRenderInlineFK(t *testing.T) {
	tests := []struct {
		name     string
		quote    byte
		table    string
		columns  []string
		expected string
	}{
		{"PostgreSQL", '"', "users", []string{"id"}, `REFERENCES "users" ("id")`},
		{"MySQL", '`', "users", []string{"id"}, "REFERENCES `users` (`id`)"},
		{"MultiColumn", '"', "orders", []string{"user_id", "order_id"}, `REFERENCES "orders" ("user_id", "order_id")`},
		{"NoColumns", '"', "users", nil, `REFERENCES "users"`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, renderInlineFK(TestDialect{quote: tt.quote}, tt.table, tt.columns),
				"Should render the correct inline FK clause")
		})
	}
}

// TestRenderTableForeignKey verifies table-level FOREIGN KEY constraint rendering.
func TestRenderTableForeignKey(t *testing.T) {
	cascade := ReferenceCascade
	restrict := ReferenceRestrict

	tests := []struct {
		name     string
		quote    byte
		fk       *ForeignKeyDef
		expected string
	}{
		{
			name:     "BasicFK",
			quote:    '"',
			fk:       &ForeignKeyDef{columns: []string{"user_id"}, refTable: "users", refColumns: []string{"id"}},
			expected: `FOREIGN KEY ("user_id") REFERENCES "users" ("id")`,
		},
		{
			name:     "WithOnDelete",
			quote:    '"',
			fk:       &ForeignKeyDef{columns: []string{"order_id"}, refTable: "orders", refColumns: []string{"id"}, onDelete: &cascade},
			expected: `FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE`,
		},
		{
			name:     "WithBothActions",
			quote:    '"',
			fk:       &ForeignKeyDef{columns: []string{"parent_id"}, refTable: "categories", refColumns: []string{"id"}, onDelete: &cascade, onUpdate: &restrict},
			expected: `FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE RESTRICT`,
		},
		{
			name:     "CompositeMySQL",
			quote:    '`',
			fk:       &ForeignKeyDef{columns: []string{"user_id", "order_id"}, refTable: "user_orders", refColumns: []string{"uid", "oid"}},
			expected: "FOREIGN KEY (`user_id`, `order_id`) REFERENCES `user_orders` (`uid`, `oid`)",
		},
		{
			name:     "NamedPG",
			quote:    '"',
			fk:       &ForeignKeyDef{name: "fk_orders_user", columns: []string{"user_id"}, refTable: "users", refColumns: []string{"id"}},
			expected: `CONSTRAINT "fk_orders_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id")`,
		},
		{
			name:     "NamedMySQLWithActions",
			quote:    '`',
			fk:       &ForeignKeyDef{name: "fk_items_order", columns: []string{"order_id"}, refTable: "orders", refColumns: []string{"id"}, onDelete: &cascade, onUpdate: &restrict},
			expected: "CONSTRAINT `fk_items_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, renderTableForeignKey(TestDialect{quote: tt.quote}, tt.fk),
				"Should render the correct table-level FK constraint")
		})
	}
}

// TestRenderTableKeyConstraint verifies PRIMARY KEY and UNIQUE table-level constraint rendering.
func TestRenderTableKeyConstraint(t *testing.T) {
	tests := []struct {
		name     string
		quote    byte
		keyword  string
		cName    string
		columns  []string
		expected string
	}{
		{
			name: "UnnamedPKPG", quote: '"', keyword: "PRIMARY KEY",
			columns: []string{"user_id", "product_id"}, expected: `PRIMARY KEY ("user_id", "product_id")`,
		},
		{
			name: "NamedPKPG", quote: '"', keyword: "PRIMARY KEY", cName: "pk_order_lines",
			columns: []string{"order_id", "line_id"}, expected: `CONSTRAINT "pk_order_lines" PRIMARY KEY ("order_id", "line_id")`,
		},
		{
			name: "UnnamedUniquePG", quote: '"', keyword: "UNIQUE",
			columns: []string{"email", "tenant_id"}, expected: `UNIQUE ("email", "tenant_id")`,
		},
		{
			name: "NamedUniquePG", quote: '"', keyword: "UNIQUE", cName: "uq_name_code",
			columns: []string{"name", "code"}, expected: `CONSTRAINT "uq_name_code" UNIQUE ("name", "code")`,
		},
		{
			name: "UnnamedPKMySQL", quote: '`', keyword: "PRIMARY KEY",
			columns: []string{"a", "b"}, expected: "PRIMARY KEY (`a`, `b`)",
		},
		{
			name: "NamedUniqueMySQL", quote: '`', keyword: "UNIQUE", cName: "uq_xy",
			columns: []string{"x", "y"}, expected: "CONSTRAINT `uq_xy` UNIQUE (`x`, `y`)",
		},
		{
			name: "UnnamedPKSQLite", quote: '"', keyword: "PRIMARY KEY",
			columns: []string{"col1", "col2"}, expected: `PRIMARY KEY ("col1", "col2")`,
		},
		{
			name: "SingleColumnPK", quote: '"', keyword: "PRIMARY KEY",
			columns: []string{"id"}, expected: `PRIMARY KEY ("id")`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, renderTableKeyConstraint(TestDialect{quote: tt.quote}, tt.keyword, tt.cName, tt.columns),
				"Should render the correct key constraint")
		})
	}
}

// TestRenderPartitionBy verifies PARTITION BY clause rendering for different strategies.
func TestRenderPartitionBy(t *testing.T) {
	tests := []struct {
		name     string
		quote    byte
		strategy PartitionStrategy
		columns  []string
		expected string
	}{
		{"RangeSingleColumnPG", '"', PartitionRange, []string{"created_at"}, `RANGE ("created_at")`},
		{"ListSingleColumnPG", '"', PartitionList, []string{"status"}, `LIST ("status")`},
		{"HashMultiColumnMySQL", '`', PartitionHash, []string{"user_id", "order_date"}, "HASH (`user_id`, `order_date`)"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expected, renderPartitionBy(TestDialect{quote: tt.quote}, tt.strategy, tt.columns),
				"Should render the correct partition clause")
		})
	}
}

// TestRenderColumnDef verifies full column definition rendering with types and constraints.
func TestRenderColumnDef(t *testing.T) {
	t.Run("SimpleColumn", func(t *testing.T) {
		query, args := renderColumnDef(pgDialect, "name", DataType.VarChar(100), nil)
		assert.Equal(t, `"name" VARCHAR(100)`, query, "Should render column name and type")
		assert.Empty(t, args, "Should produce no args for simple column")
	})

	t.Run("NotNullColumn", func(t *testing.T) {
		query, args := renderColumnDef(pgDialect, "email", DataType.Text(), []ColumnConstraint{NotNull()})
		assert.Equal(t, `"email" TEXT NOT NULL`, query, "Should include NOT NULL constraint")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("MultipleConstraints", func(t *testing.T) {
		constraints := []ColumnConstraint{NotNull(), Default(0)}
		query, args := renderColumnDef(pgDialect, "score", DataType.Integer(), constraints)
		assert.Equal(t, `"score" INTEGER NOT NULL DEFAULT 0`, query, "Should include all constraints in order")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("PrimaryKeyPG", func(t *testing.T) {
		constraints := []ColumnConstraint{PrimaryKey(), AutoIncrement()}
		query, args := renderColumnDef(pgDialect, "id", DataType.BigInt(), constraints)
		assert.Equal(t, `"id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY`, query,
			"Should render PG-style auto-increment")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("PrimaryKeyMySQL", func(t *testing.T) {
		constraints := []ColumnConstraint{PrimaryKey(), AutoIncrement()}
		query, args := renderColumnDef(mysqlDialect, "id", DataType.BigInt(), constraints)
		assert.Equal(t, "`id` BIGINT PRIMARY KEY AUTO_INCREMENT", query,
			"Should render MySQL-style auto-increment")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("PrimaryKeySQLite", func(t *testing.T) {
		constraints := []ColumnConstraint{PrimaryKey(), AutoIncrement()}
		query, args := renderColumnDef(sqliteDialect, "id", DataType.BigInt(), constraints)
		assert.Equal(t, `"id" INTEGER PRIMARY KEY AUTOINCREMENT`, query,
			"Should render SQLite-style auto-increment")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("InlineFK", func(t *testing.T) {
		constraints := []ColumnConstraint{References("users", "id")}
		query, args := renderColumnDef(pgDialect, "user_id", DataType.BigInt(), constraints)
		assert.Equal(t, `"user_id" BIGINT REFERENCES "users" ("id")`, query,
			"Should include inline REFERENCES clause")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("NullableColumn", func(t *testing.T) {
		constraints := []ColumnConstraint{Nullable()}
		query, args := renderColumnDef(pgDialect, "bio", DataType.Text(), constraints)
		assert.Equal(t, `"bio" TEXT NULL`, query, "Should include explicit NULL constraint")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("UniqueNotNullMySQL", func(t *testing.T) {
		constraints := []ColumnConstraint{NotNull(), Unique()}
		query, args := renderColumnDef(mysqlDialect, "email", DataType.VarChar(255), constraints)
		assert.Equal(t, "`email` VARCHAR(255) NOT NULL UNIQUE", query,
			"Should include both NOT NULL and UNIQUE")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("BoolDefaultTrueSQLite", func(t *testing.T) {
		constraints := []ColumnConstraint{Default(true)}
		query, args := renderColumnDef(sqliteDialect, "active", DataType.Boolean(), constraints)
		assert.Equal(t, `"active" INTEGER DEFAULT 1`, query,
			"SQLite should render boolean default as integer")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("BoolDefaultFalsePG", func(t *testing.T) {
		constraints := []ColumnConstraint{Default(false)}
		query, args := renderColumnDef(pgDialect, "active", DataType.Boolean(), constraints)
		assert.Equal(t, `"active" BOOLEAN DEFAULT FALSE`, query,
			"PG should render boolean default as FALSE")
		assert.Empty(t, args, "Should produce no args")
	})

	t.Run("StringDefaultIsParameterized", func(t *testing.T) {
		constraints := []ColumnConstraint{NotNull(), Default("active")}
		query, args := renderColumnDef(pgDialect, "status", DataType.VarChar(20), constraints)
		assert.Equal(t, `"status" VARCHAR(20) NOT NULL DEFAULT ?`, query,
			"Should bind string DEFAULT through a placeholder")
		assert.Equal(t, []any{"active"}, args, "Should pass the string default as a bound arg")
	})

	t.Run("RawDefaultRendersVerbatim", func(t *testing.T) {
		constraints := []ColumnConstraint{NotNull(), Default(RawDefault("CURRENT_TIMESTAMP"))}
		query, args := renderColumnDef(pgDialect, "created_at", DataType.Timestamp(), constraints)
		assert.Equal(t, `"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`, query,
			"RawDefault should render the SQL function verbatim, unquoted")
		assert.Empty(t, args, "RawDefault should not bind any args")
	})

	t.Run("PrecompiledCheck", func(t *testing.T) {
		// CHECK conditions are compiled into checkExpr before rendering (compileChecks),
		// so the renderer emits a CHECK (?) fragment carrying the compiled expression as a
		// bound arg and never needs a QueryBuilder of its own.
		checkExpr := bun.Safe(`"age" > 0`)
		constraints := []ColumnConstraint{{kind: ConstraintCheck, checkExpr: checkExpr}}
		query, args := renderColumnDef(pgDialect, "age", DataType.Integer(), constraints)
		assert.Equal(t, `"age" INTEGER CHECK (?)`, query, "Should render a CHECK clause with a placeholder")
		assert.Equal(t, []any{schema.QueryAppender(checkExpr)}, args, "Should bind the precompiled CHECK expression")
	})
}
