package orm

import (
	"fmt"
	"strings"

	"github.com/uptrace/bun/dialect"
	"github.com/uptrace/bun/schema"
)

// renderDDLString renders a bun DDL query to its SQL string using the database query generator.
// It mirrors bun's own Stringer behavior (panic on append error) and exists because several bun
// DDL queries (CREATE INDEX, ALTER TABLE ADD/DROP COLUMN, DROP INDEX, TRUNCATE) do not implement
// fmt.Stringer themselves.
func renderDDLString(db *BunDB, query schema.QueryAppender) string {
	buf, err := query.AppendQuery(db.getBunDB().QueryGen(), nil)
	if err != nil {
		panic(err)
	}

	return string(buf)
}

// DDLDialect defines the dialect methods needed by DDL renderers.
// Schema.Dialect satisfies this interface implicitly.
type DDLDialect interface {
	// Name returns the dialect name (e.g., pgdialect, mysqldialect, sqlitedialect).
	Name() dialect.Name
	// IdentQuote returns the character used to quote identifiers (e.g., '"' for PostgreSQL, '`' for MySQL).
	IdentQuote() byte
}

// renderColumnDef renders a complete column definition as a Bun-compatible query string with args.
// The returned query uses ? Placeholders for dynamic args (e.g., CHECK conditions).
func renderColumnDef(
	d DDLDialect,
	name string,
	dt DataTypeDef,
	constraints []ColumnConstraint,
	qb QueryBuilder,
) (string, []any) {
	var (
		sb   strings.Builder
		args []any
	)

	sb.WriteString(quoteIdent(d.IdentQuote(), name))
	sb.WriteByte(' ')
	sb.WriteString(dt.render(d.Name()))

	for _, c := range constraints {
		switch c.kind {
		case ConstraintCheck:
			// qb is required to compile the condition. Production callers always pass a
			// non-nil builder, so a nil qb is a programming error and panics here rather
			// than silently dropping the constraint.
			sb.WriteString(" CHECK (?)")

			args = append(args, qb.BuildCondition(c.checkBuilder))
		case ConstraintDefault:
			fragment, defaultArgs := renderDefault(d.Name(), c.defaultValue)

			sb.WriteByte(' ')
			sb.WriteString(fragment)

			args = append(args, defaultArgs...)

		default:
			if fragment := renderConstraint(d, c); fragment != "" {
				sb.WriteByte(' ')
				sb.WriteString(fragment)
			}
		}
	}

	return sb.String(), args
}

// renderConstraint renders a single column constraint SQL fragment that carries no bound args.
// DEFAULT (which may bind a literal) and CHECK (which binds a condition) are handled directly
// in renderColumnDef.
func renderConstraint(d DDLDialect, c ColumnConstraint) string {
	switch c.kind {
	case ConstraintNotNull:
		return "NOT NULL"
	case ConstraintNullable:
		return "NULL"
	case ConstraintPrimaryKey:
		return "PRIMARY KEY"
	case ConstraintUnique:
		return "UNIQUE"
	case ConstraintAutoIncrement:
		return renderAutoIncrement(d.Name())
	case ConstraintReferences:
		return renderInlineFK(d.IdentQuote(), c.refTable, c.refColumns)
	default:
		return ""
	}
}

// renderDefault renders a DEFAULT clause and any bound args. String literals are bound through a
// ? placeholder so the driver applies dialect-correct escaping (hand-rolled single-quote doubling
// is unsafe on MySQL with backslash escaping enabled). NULL, booleans, and numerics render as SQL
// keywords/literals with no bound args.
func renderDefault(dialectName dialect.Name, value any) (string, []any) {
	if value == nil {
		return "DEFAULT NULL", nil
	}

	switch v := value.(type) {
	case string:
		return "DEFAULT ?", []any{v}
	case bool:
		return renderDefaultBool(dialectName, v), nil
	default:
		return fmt.Sprintf("DEFAULT %v", v), nil
	}
}

// renderDefaultBool renders a DEFAULT clause for boolean values with dialect-specific handling.
func renderDefaultBool(dialectName dialect.Name, v bool) string {
	if dialectName == dialect.SQLite {
		if v {
			return "DEFAULT 1"
		}

		return "DEFAULT 0"
	}

	if v {
		return "DEFAULT TRUE"
	}

	return "DEFAULT FALSE"
}

// renderAutoIncrement renders the dialect-specific auto-increment clause.
func renderAutoIncrement(dialectName dialect.Name) string {
	switch dialectName {
	case dialect.PG:
		return "GENERATED BY DEFAULT AS IDENTITY"
	case dialect.SQLite:
		return "AUTOINCREMENT"
	default:
		return "AUTO_INCREMENT"
	}
}

// renderInlineFK renders an inline REFERENCES constraint.
func renderInlineFK(quote byte, table string, columns []string) string {
	var sb strings.Builder

	sb.WriteString("REFERENCES ")
	sb.WriteString(quoteIdent(quote, table))

	if len(columns) > 0 {
		sb.WriteString(" (")
		sb.WriteString(joinQuotedIdents(quote, columns))
		sb.WriteByte(')')
	}

	return sb.String()
}

// renderTableForeignKey renders a full table-level FOREIGN KEY constraint.
// The output includes "FOREIGN KEY" prefix and optional "CONSTRAINT name".
func renderTableForeignKey(quote byte, fk *ForeignKeyDef) string {
	var sb strings.Builder

	if fk.name != "" {
		sb.WriteString("CONSTRAINT ")
		sb.WriteString(quoteIdent(quote, fk.name))
		sb.WriteByte(' ')
	}

	sb.WriteString("FOREIGN KEY (")
	sb.WriteString(joinQuotedIdents(quote, fk.columns))
	sb.WriteString(") REFERENCES ")
	sb.WriteString(quoteIdent(quote, fk.refTable))
	sb.WriteString(" (")
	sb.WriteString(joinQuotedIdents(quote, fk.refColumns))
	sb.WriteByte(')')

	if fk.onDelete != nil {
		sb.WriteString(" ON DELETE ")
		sb.WriteString(fk.onDelete.String())
	}

	if fk.onUpdate != nil {
		sb.WriteString(" ON UPDATE ")
		sb.WriteString(fk.onUpdate.String())
	}

	return sb.String()
}

// renderTableKeyConstraint renders a table-level key constraint (PRIMARY KEY or UNIQUE).
func renderTableKeyConstraint(quote byte, keyword, name string, columns []string) string {
	var sb strings.Builder

	if name != "" {
		sb.WriteString("CONSTRAINT ")
		sb.WriteString(quoteIdent(quote, name))
		sb.WriteByte(' ')
	}

	sb.WriteString(keyword)
	sb.WriteString(" (")
	sb.WriteString(joinQuotedIdents(quote, columns))
	sb.WriteByte(')')

	return sb.String()
}

// renderPartitionBy renders a PARTITION BY clause.
func renderPartitionBy(quote byte, strategy PartitionStrategy, columns []string) string {
	return strategy.String() + " (" + joinQuotedIdents(quote, columns) + ")"
}

// quoteIdent quotes an identifier using dialect.AppendName for proper escaping.
func quoteIdent(quote byte, name string) string {
	return string(dialect.AppendName(nil, name, quote))
}

// joinQuotedIdents joins identifiers with commas, quoting each using dialect.AppendName.
func joinQuotedIdents(quote byte, idents []string) string {
	var sb strings.Builder
	for i, ident := range idents {
		if i > 0 {
			sb.WriteString(", ")
		}

		sb.WriteString(quoteIdent(quote, ident))
	}

	return sb.String()
}
