package buildinfo

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerate(t *testing.T) {
	t.Run("WritesParseableFileInNestedDir", func(t *testing.T) {
		outputPath := filepath.Join(t.TempDir(), "internal", "vef", "build_info.go")

		require.NoError(t, Generate(outputPath, "vef"), "Generate should create the build info file and its parent directories")

		content, err := os.ReadFile(outputPath)
		require.NoError(t, err, "generated file should be readable")

		src := string(content)
		assert.Contains(t, src, "// Code generated by vef-cli. DO NOT EDIT.", "output should carry the generated-code header")
		assert.Contains(t, src, "package vef", "output should declare the requested package")
		assert.Contains(t, src, "monitor.BuildInfo", "output should reference monitor.BuildInfo")
		assert.Contains(t, src, "AppVersion:", "output should populate AppVersion")
		assert.Contains(t, src, "BuildTime:", "output should populate BuildTime")
		assert.Contains(t, src, "GitCommit:", "output should populate GitCommit")

		_, parseErr := parser.ParseFile(token.NewFileSet(), outputPath, content, parser.AllErrors)
		require.NoError(t, parseErr, "generated file should be valid, gofmt-able Go source")
	})

	t.Run("WritesIntoCurrentDirWithoutMkdir", func(t *testing.T) {
		outputPath := filepath.Join(t.TempDir(), "build_info.go")

		require.NoError(t, Generate(outputPath, "main"), "Generate should write a file with no directory component")

		content, err := os.ReadFile(outputPath)
		require.NoError(t, err, "generated file should be readable")
		assert.Contains(t, string(content), "package main", "output should declare the default package")
	})
}
