package mcp

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/invopop/jsonschema"
)

// reflector is a pre-configured jsonschema reflector for MCP.
var reflector = &jsonschema.Reflector{
	// Anonymous prevents $id from being generated based on package path.
	Anonymous: true,
	// DoNotReference inlines nested types instead of using $ref.
	DoNotReference: true,
	// RequiredFromJSONSchemaTags uses jsonschema:"required" tag to mark required fields.
	RequiredFromJSONSchemaTags: true,
}

// SchemaFor returns a JSON Schema for the type T.
// This follows the same naming convention as reflect.TypeFor.
//
// The generated schema is suitable for use as MCP Tool.InputSchema or output schema.
//
// Usage:
//
//	type MyInput struct {
//	    Name string `json:"name" jsonschema:"required,description=The name"`
//	    Age  int    `json:"age,omitempty" jsonschema:"minimum=0,maximum=150"`
//	}
//
//	schema := mcp.SchemaFor[MyInput]()
//
// Supported jsonschema tags (use `jsonschema:"tag1,tag2=value"`):
//
// Generic (all types):
//   - required: marks the field as required
//   - title=xxx: field title
//   - description=xxx: field description
//   - default=xxx: default value
//   - example=xxx: example value (can be repeated)
//   - enum=A,enum=B: enumeration values
//   - oneof_type=string;integer: field can be one of multiple types
//   - anyof_type=string;integer: field can be any of multiple types
//
// String type:
//   - minLength=N: minimum string length
//   - maxLength=N: maximum string length
//   - pattern=xxx: regex pattern
//   - format=xxx: format hint (email, uri, uuid, date-time, date, time, ipv4, ipv6, etc.)
//   - readOnly=true: field is read-only
//   - writeOnly=true: field is write-only
//
// Number/Integer type:
//   - minimum=N: minimum value
//   - maximum=N: maximum value
//   - exclusiveMinimum=N: exclusive minimum value
//   - exclusiveMaximum=N: exclusive maximum value
//   - multipleOf=N: value must be multiple of N
//
// Array type:
//   - minItems=N: minimum array length
//   - maxItems=N: maximum array length
//   - uniqueItems=true: items must be unique
//
// Additional tags:
//   - jsonschema_description:"xxx": standalone description tag
//   - jsonschema_extras:"a=b,c=d": add custom schema properties
func SchemaFor[T any]() map[string]any {
	schema, _ := schemaFromType(reflect.TypeFor[T]())

	return schema
}

// SchemaOf returns a JSON Schema for the type of v.
// This follows the same naming convention as reflect.TypeOf.
//
// If v is nil, SchemaOf returns nil.
func SchemaOf(v any) map[string]any {
	if v == nil {
		return nil
	}

	schema, _ := schemaFromType(reflect.TypeOf(v))

	return schema
}

// MustSchemaFor is like SchemaFor but panics with the underlying cause when
// schema generation fails.
func MustSchemaFor[T any]() map[string]any {
	schema, err := schemaFromType(reflect.TypeFor[T]())
	if err != nil {
		panic(fmt.Errorf("mcp: generate schema: %w", err))
	}

	return schema
}

// MustSchemaOf is like SchemaOf but panics. It panics on a nil value (no type to
// reflect) and on a schema-generation failure, surfacing the underlying cause in
// the latter case.
func MustSchemaOf(v any) map[string]any {
	if v == nil {
		panic("mcp: cannot generate schema for nil value")
	}

	schema, err := schemaFromType(reflect.TypeOf(v))
	if err != nil {
		panic(fmt.Errorf("mcp: generate schema: %w", err))
	}

	return schema
}

// schemaFromType generates JSON Schema from a reflect.Type. The marshal and
// unmarshal failures it reports are effectively unreachable for reflector
// output, but are propagated rather than swallowed so the Must* variants can
// surface the real cause instead of a nil result.
func schemaFromType(t reflect.Type) (map[string]any, error) {
	schema := reflector.ReflectFromType(t)

	jsonBytes, err := json.Marshal(schema)
	if err != nil {
		return nil, fmt.Errorf("marshal reflected schema: %w", err)
	}

	var resultVal map[string]any
	if err := json.Unmarshal(jsonBytes, &resultVal); err != nil {
		return nil, fmt.Errorf("unmarshal schema into map: %w", err)
	}

	// $schema is always generated by the library, must be removed for MCP
	delete(resultVal, "$schema")

	return resultVal, nil
}
